---
- name: ensure pip installed
  apt: pkg=python-pip state=latest

- name: ensure python-dev installed
  apt: pkg=python-dev state=latest

# TODO: make requirements.txt file and pin dependency versions?
- name: pip install celery and dependencies
  pip: name={{ item }} state=latest
  with_items:
    - librabbitmq
    - requests
    - celery
    - flower
