---
- name: setup machine
  hosts: all:!local # all
  sudo: yes
  roles:
    - role: common

- name: install rbenv and ruby
  hosts: webservers # webservers
  sudo: yes
  roles:
    - role: ruby-multi
      versions: $ruby_versions

- name: install nginx
  hosts: webservers # webservers
  sudo: yes
  roles:
    - role: nginx

- name: install mongodb
  hosts: dbservers # dbservers
  sudo: yes
  roles:
    - role: mongodb
    - role: mongodb-firewall

- name: install node
  hosts: webservers:matchurls # webservers:matchurls
  sudo: yes
  roles:
    - role: nodejs

# TODO: split installing from deploying?
- name: install dota2rails app
  hosts: webservers # webservers
  remote_user: "{{ web.deploy_user }}"
  sudo: no
  roles:
    - role: dota2rails

- name: install rabbitmq
  hosts: mqservers # mqservers
  sudo: yes
  roles:
    - role: rabbitmq

- name: install celery
  hosts: mqservers # mqservers
  sudo: yes
  roles:
    - role: celery

- name: alacrity submodules
  hosts: local # local
  tasks:
    - name: update submodules
      command: git submodule update --init --recursive chdir=..

- name: install and run alacrity
  hosts: mqservers # mqservers
  sudo: yes
  roles:
    - role: alacrity

- name: install/run matchurls
  hosts: matchurls # matchurls
  sudo: no
  roles:
    - role: matchurls
