---
- name: setup machine
  hosts: none # all
  sudo: yes
  roles:
    - role: common

- name: install rbenv and ruby
  hosts: webservers # webservers
  sudo: yes
  roles:
    - role: ruby-multi
      versions: $ruby_versions

- name: install nodejs
  hosts: webservers # webservers
  sudo: yes
  roles:
    - role: nodejs

- name: install nginx
  hosts: webservers # webservers
  sudo: yes
  roles:
    - role: nginx

- name: install mongodb
  hosts: dbservers # dbservers
  sudo: yes
  roles:
    - role: mongodb
    - role: mongodb-firewall

# TODO: split installing from deploying?
- name: install dota2rails app
  hosts: special
  remote_user: "{{ deploy_user }}"
  sudo: no
  roles:
    - role: dota2rails

- name: install rabbitmq
  hosts: mqservers # mqservers
  sudo: yes
  roles:
    - role: rabbitmq

- name: install celery
  hosts: mqservers # mqservers
  sudo: no
  roles:
    - role: celery

- name: install and run alacrity

# TODO: gems and stuff or using capistrano too?
